# Learn more about configuring your app at https://d3alyhq6sarjuz.cloudfront.net/docs/apps/tools/cli/configuration

client_id = "57b6e209afc603655aedaa6ac555309f"
name = "payment"
handle = "payment-113"
application_url = "https://d3alyhq6sarjuz.cloudfront.net"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "standbox.myshopify.com"
include_config_on_deploy = true

[access_scopes]
scopes = "read_customers,read_payment_customizations,read_translations,write_payment_customizations"

[auth]
redirect_urls = [
  "https://d3alyhq6sarjuz.cloudfront.net/auth/callback",
  "https://d3alyhq6sarjuz.cloudfront.net/auth/shopify/callback",
  "https://d3alyhq6sarjuz.cloudfront.net/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
