# Extension-only app — no admin UI. Deploy with `shopify app deploy`.

client_id = "57b6e209afc603655aedaa6ac555309f"
name = "payment"
handle = "payment-113"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "standbox.myshopify.com"

[access_scopes]
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2025-10"

[pos]
embedded = false
