# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "57b6e209afc603655aedaa6ac555309f"
name = "payment"
handle = "payment-113"
application_url = "https://d2zl0po73iay2p.cloudfront.net"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "standbox.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_payment_customizations,write_payment_customizations,write_products"

[auth]
redirect_urls = [
  "https://d2zl0po73iay2p.cloudfront.net/auth/callback",
  "https://d2zl0po73iay2p.cloudfront.net/auth/shopify/callback",
  "https://d2zl0po73iay2p.cloudfront.net/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false

