api_version = "2026-04"
uid = "4f8a281d-8599-ed4f-dd32-1297c2872b96939fbf00"

[[extensions]]
handle = "payment-customization"
name = "t:name"
description = "t:description"
type = "function"

  [[extensions.targeting]]
  target = "purchase.payment-customization.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"

  [extensions.input.variables]
  namespace = "payment-customization"
  key = "function-configuration"
