name: CI
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  lint:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Function tests
        run: npm run test:function
      - name: eslint
        run: npx eslint extensions/
      - name: prettier check
        run: npx prettier --check .

  function-test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build function
        run: |
          cd extensions/payment-customization
          npx shopify app function build
      - name: tests
        run: npm run test:function
