name: Deploy to production
on:
  push:
    branches:
      - main
jobs:
  shopify-deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          npm install -g @shopify/cli
          npm install
      - name: Deploy Shopify app + payment-customization function
        env:
          SHOPIFY_CLI_PARTNERS_TOKEN: ${{ secrets.SHOPIFY_CLI_PARTNERS_TOKEN }}
        run: |
          shopify app deploy --force \
            --source-control-url "${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
